### ISSUE TITLE
Add DSA Questions

### ISSUE THREAD

**Issue by PriyanshuGarg26** [ar7aditya/DSA#39]
I want to add DSA questions like 2Sum, 3Sum , reverse linked list.

**Comment by beastvarun** [comment]
I want to add a DSA questions, please assign me this.
My DSA solution will be of: A Program to compare two strings without using library function.in c language.

**Comment by PriyanshuGarg26** [comment]
> I want to add DSA questions like 2Sum, 3Sum , reverse linked list.

Pls assign this issue to me.

**Comment by Faizan96322** [comment]
hey, I would like to add finding middle number of a linked list in a very optimised way, can you please assign me this task under hacktoberfest-2022

**Comment by shubhankarsharma876** [comment]
I want to contribute with some of the questions which are important in prospective to improve the skills of DSA like using algorithm of "Moores Voting Algorithm" , "Dutch National glag Algorithm" etc. Which are highly involved in interviews as well.   
I would be glad to be assigned with this issue.

**Comment by chhotu2** [comment]
@PriyanshuGarg26  I want to contribute some question which are very important to improve the skill of DSA like  Binary search in 2D, sorting(Selection sort, Merge sort, Bubble sort, Insertion sort etc. ) , Linked list Sorting, Linked list Palindrome, Merge Linked list  etc. These topic are very important. So  please assign this issue to me.

**Comment by Ayushitgithub** [comment]
hey sir i want to contribute to this issue plz assign me this issue...

**Comment by nirbhaykr87** [comment]
I want to add DSA Question 
Please assign this issue to me.

**Comment by PriyanshuGarg26** [comment]
Closed!
