### ISSUE TITLE
Codeforces Solution for question 118A and 144A

### ISSUE THREAD

**Issue by Tanmay20030516** [ar7aditya/DSA#47]
Codeforces Solution for question 118A and 144A

**Comment by ganajayant** [comment]
can i have this issue

**Comment by Shivashish-rwt** [comment]
@Tanmay20030516 
I can do it. Can u please assign it to me?

**Comment by Tanmay20030516** [comment]
I've already PR ed those. Apologies for poor communication

**Comment by ayushs-2k4** [comment]
Hey, I am interested in this issue, I have done some leetcode also. So I think I will be able to do it. So if you are comfortable, assign it to me.

**Comment by Ayushitgithub** [comment]
hey sir i am interested in solving this issue plz assign me this

**Comment by Tanmay20030516** [comment]
😇
