### ISSUE TITLE
Square root of a number using binary search

### ISSUE THREAD

**Issue by AdityaMore7000** [ar7aditya/DSA#56]
Hello @ar7aditya, 

I would like to add a code that finds the square root of a number depending upon the choice of user. Output will be a floating point number, and the user can explicitly set precision for the answer that he/she wants. I will write code in C++ with accompanied by comments so that it can be easily understood by the user

Kindly assign me this task, and give me the opportunity to contribute in your repository. Looking forward for your response

**Comment by ar7aditya** [comment]
> Hello @ar7aditya,
> 
> I would like to add a code that finds the square root of a number depending upon the choice of user. Output will be a floating point number, and the user can explicitly set precision for the answer that he/she wants. I will write code in C++ with accompanied by comments so that it can be easily understood by the user
> 
> Kindly assign me this task, and give me the opportunity to contribute in your repository. Looking forward for your response

I'm glad that you reached out to me . Yes you can contribute go ahead
